### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by alranel** [italia/lg-acquisizione-e-riuso-software-per-pa-docs-en#1]
This repo needs a README similar to what we have for the Italian version:
https://github.com/italia/lg-acquisizione-e-riuso-software-per-pa-docs

**Comment by mamatteo** [comment]
Esiste già la versione tradotta o va fatta?

**Comment by libremente** [comment]
@mamatteo purtroppo la versione tradotta di quel README non esiste e quindi andrebbe fatta. 
In prima battuta potrebbe anche andar bene una versione compatta di [quella in Italiano](https://github.com/italia/lg-acquisizione-e-riuso-software-per-pa-docs) e poi a tendere faremo un README più robusto. L'importante è non avere un README vuoto.

**Comment by libremente** [comment]
Translate README into English

**Comment by libremente** [comment]
Done, closing.
