### ISSUE TITLE
Split into chapters

### ISSUE THREAD

**Issue by alranel** [italia/lg-acquisizione-e-riuso-software-per-pa-docs-en#2]
This repo now contains a single page.
We should split them in order to arrange chapters like the Italian version: https://github.com/italia/lg-acquisizione-e-riuso-software-per-pa-docs

**Comment by mamatteo** [comment]
Done!

**Comment by libremente** [comment]
Grazie @mamatteo. 
Appena facciamo il merge chiudo.
