### ISSUE TITLE
Fix formatting

### ISSUE THREAD

**Issue by alranel** [italia/lg-acquisizione-e-riuso-software-per-pa-docs-en#3]
Headers and other things were converted incorrectly. Make sure the appearance is similar to the Italian version: https://github.com/italia/lg-acquisizione-e-riuso-software-per-pa-docs

**Comment by mamatteo** [comment]
Done!

**Comment by libremente** [comment]
Grazie @mamatteo!
Appena faccio il merge chiudo la issue.
