### ISSUE TITLE
Text style

### ISSUE THREAD

**Issue by mamatteo** [italia/lg-acquisizione-e-riuso-software-per-pa-docs-en#5]
Va allineato questo documento alla versione italiana, nello stile "evidenziato" di alcune sigle (si veda e si confronti con la versione italiana ad esempio il paragrafo **3.5.3. Choosing a licence** e la relativa sigla **"EUPL - 1.2"**

**Comment by libremente** [comment]
Penso sia solo questione di dichiarare un colore (in capo o in coda all'RST) e usare quello. Non prioritario per ora, possiamo farlo con calma.

**Comment by libremente** [comment]
@mamatteo qual è il metodo più veloce per risolvere questa issue? Bisogna mettere a mano le `` attorno al testo da evidenziare facendo un diff visuale con la versione in italiano?

**Comment by mamatteo** [comment]
@libremente Direi proprio di sì
